import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Activity, ArrowDownToLine, Bot, ExternalLink, FileCheck2, Fingerprint, Landmark, Library, ShieldCheck } from 'lucide-react';
import { apiFetch } from '../lib/api';
import { PageHeader } from '../components/ui/PageHeader';
import { HashBadge } from '../components/ui/HashBadge';
import { Drawer } from '../components/ui/Drawer';
import { Skeleton } from '../components/ui/Skeleton';
import { Button } from '../components/ui/Button';

type Passport = {
  id: string; disclaimer: string;
  problem_and_kpis: { challenge_id: string; title: string; problem?: string; measurement_plan?: Record<string, unknown>; results: Array<{kpi:string;claimed:number|null;recomputed:number|null;delta:number|null;outcome:string;explanation:string}> };
  eligibility: { agreement_status:string; terms_accepted:boolean };
  agreement_version?: {version:number;template:string;template_version:number;approved:boolean;change_note:string}|null;
  evidence_and_results?: {filename:string;sha256:string;rows:number;version:number;integrity_check:string;submitted_at:string}|null;
  validation?: {action:string;reason:string|null;recorded_at:string}|null;
  milestones_and_payments:Array<{id:string;code:string;title:string;amount:number;state:string;invoice?:{status:string;reference?:string;sha256?:string}|null;payment?:{status:string;reference:string;simulated:boolean}|null}>;
  scale_up_recommendation?: {technical_suitability:string;procurement_route_status:string;findings:Array<{dimension:string;decision:string;reason:string}>}|null;
  procurement_route:{status:string;note:string}; policy_sources:Array<{title:string;jurisdiction:string;version:string;effective_date:string;url:string;notes:string}>;
  audit_chain:{valid:boolean;checked_events:number;message:string}; public_verify_path:string;
};

export default function PassportPage() {
  const { id = 'demo-agreement' } = useParams();
  const [record,setRecord]=useState<Passport|null>(null); const [error,setError]=useState(''); const [policyOpen,setPolicyOpen]=useState(false); const [assistantOpen,setAssistantOpen]=useState(false); const [answer,setAnswer]=useState('');
  useEffect(()=>{ let active=true; apiFetch(`/api/passports/${encodeURIComponent(id)}`).then(async (res)=>{const body=await res.json();if(!res.ok)throw new Error(body.detail||'Passport unavailable.');if(active)setRecord(body);}).catch((e)=>{if(active)setError(e instanceof Error?e.message:'Passport unavailable.');});return()=>{active=false};},[id]);
  const download=async (kind:'json'|'pdf')=>{try{const res=await apiFetch(`/api/passports/${encodeURIComponent(id)}/${kind==='json'?'export.json':'decision-package.pdf'}`);if(!res.ok)throw new Error('Export could not be generated.');const blob=await res.blob();const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=`${kind==='json'?'pilot-passport':'decision-package'}-${id}.${kind==='json'?'json':'pdf'}`;a.click();URL.revokeObjectURL(href);}catch(e){setError(e instanceof Error?e.message:'Export failed.');}};
  return <div className='mx-auto max-w-6xl space-y-6 p-6 lg:p-9'>
    <PageHeader title='Pilot evidence passport' eyebrow='Structured project record' description='A portable view of the pilot baseline, evidence, decisions, and recorded milestones.' actionSlot={<div className='flex gap-2'><Button variant='outline' onClick={()=>void download('json')}><ArrowDownToLine size={16}/>JSON</Button><Button onClick={()=>void download('pdf')}><ArrowDownToLine size={16}/>Decision package</Button></div>}/>
    {error&&<div role='alert' className='rounded-xl border border-danger/30 bg-danger/10 p-4 text-sm text-danger'>{error}</div>}
    {!record?<Skeleton className='h-[520px]'/>:<>
      <div className='flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-primary/15 bg-gradient-to-r from-primary/10 to-surface p-5'><div><div className='flex items-center gap-2 text-sm font-semibold text-warning'><ShieldCheck size={18}/> Passport · {record.id}</div><p className='mt-1 text-xs text-warning/70'>{record.disclaimer}</p></div><div className='flex flex-wrap gap-2'><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${record.audit_chain.valid?'bg-success/10 text-success':'bg-danger/10 text-danger'}`}>Audit chain {record.audit_chain.valid?'verified':'failed'}</span><span className='rounded-full bg-surface/80 px-3 py-1.5 text-xs font-medium text-warning'>Procurement: {record.procurement_route.status}</span><a href={`/verify/${encodeURIComponent(id)}`} target='_blank' rel='noreferrer' className='inline-flex items-center gap-1 rounded-full bg-surface px-3 py-1.5 text-xs font-semibold text-text'>Public verify <ExternalLink size={13}/></a></div></div>
      {record.evidence_and_results&&<div className='flex flex-wrap items-center gap-2 rounded-xl border border-border bg-surface px-4 py-3 text-xs text-muted'><Fingerprint size={15}/><span>Evidence SHA-256</span><HashBadge value={record.evidence_and_results.sha256}/><span className='rounded-full bg-success/10 px-2 py-1 font-medium text-success'>{record.evidence_and_results.integrity_check}</span></div>}
      <div className='grid gap-5 lg:grid-cols-2'>
        <section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold text-text'>Problem & locked KPIs</h2><p className='mt-1 text-sm text-muted'>{record.problem_and_kpis.title}</p>{record.problem_and_kpis.problem&&<p className='mt-3 text-sm leading-relaxed text-text'>{record.problem_and_kpis.problem}</p>}<div className='mt-4 space-y-2'>{record.problem_and_kpis.results.map((k)=><div key={k.kpi} className='rounded-xl bg-bg p-3'><div className='flex justify-between gap-2 text-sm'><strong className='text-text'>{k.kpi}</strong><span className='font-semibold text-primary'>{k.outcome.replace('_',' ')}</span></div><p className='mt-1 text-xs text-muted'>Claim {k.claimed??'—'} → recomputed {k.recomputed??'—'}{k.delta!=null?` · Δ ${k.delta}`:''}</p><p className='mt-1 text-xs leading-relaxed text-muted'>{k.explanation}</p></div>)}</div></section>
        <section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold text-text'>Eligibility & agreement</h2><div className='mt-4 grid grid-cols-2 gap-3 text-sm'><div className='rounded-xl bg-bg p-3'><p className='text-xs text-muted'>Agreement state</p><strong className='mt-1 block text-text'>{record.eligibility.agreement_status}</strong></div><div className='rounded-xl bg-bg p-3'><p className='text-xs text-muted'>Startup terms</p><strong className='mt-1 block text-text'>{record.eligibility.terms_accepted?'Accepted':'Pending'}</strong></div></div>{record.agreement_version&&<div className='mt-3 rounded-xl border border-border p-3 text-sm'><div className='flex items-center gap-2 font-medium text-text'><FileCheck2 size={16}/>Version {record.agreement_version.version} · {record.agreement_version.template} v{record.agreement_version.template_version}</div><p className='mt-1 text-xs text-muted'>{record.agreement_version.change_note}</p></div>}{record.evidence_and_results&&<p className='mt-3 text-xs text-muted'>{record.evidence_and_results.filename} · v{record.evidence_and_results.version} · {record.evidence_and_results.rows} source rows</p>}</section>
        <section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold text-text'>Validation & evidence thread</h2><div className='relative mt-4 space-y-4 before:absolute before:bottom-3 before:left-[9px] before:top-3 before:w-px before:bg-border'>{record.evidence_and_results&&<div className='relative flex gap-3'><span className='z-10 mt-1 h-2.5 w-2.5 rounded-full bg-primary ring-4 ring-surface'/><div><p className='text-sm font-medium text-text'>Evidence submitted · v{record.evidence_and_results.version}</p><p className='text-xs text-muted'>{record.evidence_and_results.submitted_at}</p></div></div>}{record.validation&&<div className='relative flex gap-3'><span className='z-10 mt-1 h-2.5 w-2.5 rounded-full bg-success/100 ring-4 ring-surface'/><div><p className='text-sm font-medium capitalize text-text'>Validator {record.validation.action.replace('_',' ')}</p><p className='text-xs text-muted'>{record.validation.reason||'No additional note.'}</p></div></div>}<div className='relative flex gap-3'><span className='z-10 mt-1 h-2.5 w-2.5 rounded-full bg-primary ring-4 ring-surface'/><div><p className='text-sm font-medium text-text'>Audit trail</p><p className='text-xs text-muted'>{record.audit_chain.message} · {record.audit_chain.checked_events} events</p></div></div></div></section>
        <section className='rounded-2xl border border-border bg-surface p-5'><div className='flex items-center justify-between'><h2 className='font-semibold text-text'>Milestones & payment trail</h2><span className='text-[10px] text-muted'>Simulated settlement only</span></div><div className='mt-4 space-y-2'>{record.milestones_and_payments.map((m)=><div key={m.id} className='rounded-xl border border-border p-3'><div className='flex justify-between gap-2 text-sm'><strong className='text-text'>{m.code} · {m.title}</strong><span className='text-xs font-medium text-primary'>{m.state}</span></div><div className='mt-1 text-xs text-muted'>{m.invoice?`Invoice ${m.invoice.reference||''} · ${m.invoice.status}`:'No invoice recorded'}{m.payment?` · ${m.payment.status} · ${m.payment.reference}`:''}</div></div>)}</div></section>
        <section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold text-text'>Scale-up recommendation</h2>{record.scale_up_recommendation?<><p className='mt-1 text-sm text-text'>Technical suitability: <strong>{record.scale_up_recommendation.technical_suitability}</strong></p><p className='text-sm text-muted'>Procurement route: {record.scale_up_recommendation.procurement_route_status}</p><div className='mt-3 space-y-2'>{record.scale_up_recommendation.findings.map((f)=><p key={f.dimension} className='rounded-lg bg-bg p-2 text-xs text-muted'><strong className='capitalize text-text'>{f.dimension}: {f.decision}.</strong> {f.reason}</p>)}</div></>:<p className='mt-2 text-sm text-muted'>No receiving-district assessment recorded.</p>}</section>
        <section className='rounded-2xl border border-border bg-surface p-5'><div className='flex items-center gap-2'><Landmark size={17} className='text-primary'/><h2 className='font-semibold text-text'>Procurement route</h2></div><p className='mt-2 text-sm font-medium text-text'>{record.procurement_route.status}</p><p className='mt-1 text-sm text-muted'>{record.procurement_route.note||'Route approval is recorded separately from technical performance.'}</p></section>
      </div>
      <section className='rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/10 to-surface p-5'><div className='flex flex-wrap items-center justify-between gap-3'><div><div className='flex items-center gap-2 font-semibold text-text'><Bot size={18} className='text-primary'/>Violet · record-grounded assistant</div><p className='mt-1 text-xs text-muted'>Answers below cite this passport’s saved records only.</p></div><Button variant='outline' onClick={()=>{setAssistantOpen((v)=>!v);setAnswer('');}}>{assistantOpen?'Close assistant':'Explain this decision'}</Button></div>{assistantOpen&&<div className='mt-4 rounded-xl bg-surface p-4 text-sm leading-relaxed text-text'><p>{record.scale_up_recommendation?`The technical result is “${record.scale_up_recommendation.technical_suitability}” because the receiving-district assessment compares the saved pilot conditions dimension by dimension. Procurement remains “${record.procurement_route.status}” and is not inferred from technical suitability.`:'This passport has no saved transfer assessment yet, so I cannot explain a scale-up outcome from the project record.'}</p><p className='mt-2 text-xs font-medium text-primary'>Citations: Pilot evidence passport · Scale-up recommendation · Procurement route</p><button onClick={()=>setAnswer('मराठीत: हा तांत्रिक निष्कर्ष जिल्ह्याच्या अटी आणि पायलट पुराव्याची तुलना करतो. खरेदी मंजुरी हा वेगळा निर्णय आहे. (स्रोत: Pilot evidence passport → Scale-up recommendation)')} className='mt-3 rounded-lg border border-primary px-3 py-2 text-xs font-semibold text-primary'>Explain in simple Marathi</button>{answer&&<p className='mt-2 rounded-lg bg-primary/10 p-3 text-xs text-text'>{answer}</p>}</div>}</section>
      <section className='flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border bg-surface p-5'><div className='flex items-center gap-2'><Library size={17} className='text-primary'/><div><h2 className='font-semibold text-text'>Applicable policy sources</h2><p className='text-xs text-muted'>{record.policy_sources.length} source(s) saved with the workspace</p></div></div><Button variant='outline' onClick={()=>setPolicyOpen(true)}>Which rule applied?</Button></section>
    </>}
    <Drawer open={policyOpen} onClose={()=>setPolicyOpen(false)}><div className='flex h-full flex-col'><h2 className='text-lg font-semibold text-text'>Which rule applied?</h2><p className='mt-1 text-xs text-muted'>Policy sources available in the project record.</p><div className='mt-5 flex-1 space-y-3 overflow-auto'>{record?.policy_sources.map((p)=><article key={`${p.version}-${p.title}`} className='rounded-xl border border-border p-4'><h3 className='font-medium text-text'>{p.title}</h3><p className='mt-1 text-xs text-muted'>{p.jurisdiction} · {p.version} · Effective {p.effective_date}</p><p className='mt-2 text-xs text-muted'>{p.notes}</p><a className='mt-2 inline-block text-xs font-medium text-primary' href={p.url} target='_blank' rel='noreferrer'>Open source ↗</a></article>)||<p className='text-sm text-muted'>No policy sources are attached to this record.</p>}</div><p className='border-t border-border pt-3 text-xs text-muted'>Approver identity and version-to-version policy diffs are not available in this project record.</p></div></Drawer>
  </div>;
}
